verbose: true
connection:
  port: 8080
server:
  debug:
    log: '*'
plugins:
  vision:
  hapi-nonexistent: false
  hapi-disabled:
    _enabled: false
method: '{{serverMethod("add")}}'
oneDay: '{{ms("1d")}}'
