connection:
  port: 8080

logging:
  reporters:
    console:
      events:
        log: '*'

plugins:
  hapi-nonexistent: false
  hapi-disabled: 
    _enabled: false
  hapi-views:
  hapi-favicon:
    _priority: -1
