verbose: true
connection:
  port: 8080

server:
  debug:
    log: '*'
plugins:
  vision:
  hapi-nonexistent: false
  hapi-disabled: 
    _enabled: false
  hapi-views:
  hapi-favicon:
    _priority: -1

method: '{{serverMethod("add")}}'
